
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${MS_EMAIL_DS_HOST}:${MS_EMAIL_DS_PORT}/msmail?createDatabaseIfNotExist=true
    username: ${MS_EMAIL_DS_USER}
    password: ${MS_EMAIL_DS_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mail:
    host: ${MS_EMAIL_MAIL_HOST}
    port: ${MS_EMAIL_MAIL_PORT}
    username: ${MS_EMAIL_MAIL_USER}
    password: ${MS_EMAIL_MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

